# Generated by Django 5.1.6 on 2025-02-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='business_case_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='circuit_diagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='model_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
